apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: checkoutservice
  namespace: warden-demo
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: checkoutservice
  namespaceSelector:
    matchNames:
      - warden-demo
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
